import type { AssessmentFunction, FunctionId } from "@/types/assessment";

export const ANSWER_SCALE = [
  { value: 0, label: "Not available", detail: "This is not currently done or available." },
  { value: 1, label: "Fully manual", detail: "Execution is inconsistent and depends on individual effort." },
  { value: 2, label: "Manual but documented", detail: "A process exists, but most work is still completed manually." },
  { value: 3, label: "Digitized", detail: "A tool is used, but the workflow and data are not fully connected." },
  { value: 4, label: "Partly automated", detail: "The process is structured, measured, and partly automated." },
  { value: 5, label: "Integrated and optimized", detail: "The workflow is automated, connected, measured, and continually improved." },
] as const;

export const INDUSTRIES = [
  "Professional Services", "Retail & Distribution", "Logistics", "Manufacturing", "Construction",
  "Healthcare", "Education", "Real Estate", "Financial Services", "Technology", "Hospitality", "Other",
];

export const COMPANY_SIZES = ["1–10 employees", "11–50 employees", "51–200 employees", "201–500 employees", "500+ employees"];
export const REVENUE_RANGES = ["Pre-revenue", "Under ₦10m", "₦10m–₦50m", "₦50m–₦250m", "₦250m–₦1bn", "Above ₦1bn", "Prefer not to say"];
export const ROLES = ["Founder / CEO", "COO / Operations Leader", "CFO / Finance Leader", "Department Head", "IT / Systems Leader", "Manager", "Consultant / Adviser", "Other"];
export const CHALLENGES = [
  "Not enough leads", "Leads are not converting", "Manual processes are slowing us down",
  "Customers are not responded to quickly", "Finance/accounting is too manual", "HR processes are disorganized",
  "Inventory/logistics issues", "Poor visibility into business performance", "Too many disconnected tools",
  "Too much repetitive work", "Other",
];
export const CONSULTATION_TIMES = ["Weekday mornings", "Weekday afternoons", "Weekday evenings", "No preference"];

export const ASSESSMENT_FUNCTIONS: AssessmentFunction[] = [
  {
    id: "sales", name: "Sales Operations", shortName: "Sales", icon: "sales",
    description: "Capture leads, improve follow-up, increase conversion, strengthen pipeline visibility, and reduce lost opportunities.",
    coreQuestion: "Are you losing revenue because leads are not captured, followed up, qualified, tracked, or converted consistently?",
    dimensions: ["Lead capture", "Lead qualification", "Lead routing", "Follow-up discipline", "CRM usage", "Pipeline visibility", "Proposal workflow", "Activity tracking", "Forecasting", "Customer handover"],
    questions: [
      "How consistently do you capture new leads from your website, WhatsApp, referrals, social media, ads, walk-ins, and calls?",
      "Are all leads automatically recorded in one central system?",
      "How quickly does your team follow up after a new enquiry?",
      "Do leads get assigned automatically to the right salesperson or team?",
      "Do you have a defined lead qualification process?",
      "Can you distinguish hot, warm, and cold leads clearly?",
      "Do you use a CRM to track lead status, deal stage, next action, expected value, and close date?",
      "Are sales follow-ups automated through reminders, email, SMS, or WhatsApp?",
      "Can managers see which leads are neglected and which follow-ups are overdue?",
      "Are quotations or proposals generated from controlled templates and workflows?",
      "Can management see total pipeline value in real time?",
      "Can management see conversion rate by lead source?",
      "Do you know which marketing channels generate the best customers?",
      "Do you have automated alerts for stalled deals?",
      "Is there a structured handover from sales to operations, finance, or customer success?",
    ],
    kpis: ["Lead response time", "Lead-to-opportunity conversion", "Opportunity-to-customer conversion", "Sales cycle length", "Overdue follow-ups", "Pipeline value", "Forecast accuracy", "Proposal turnaround time", "Revenue by lead source"],
    opportunities: ["Website and WhatsApp lead capture into CRM", "Lead scoring and auto-assignment", "Automated follow-up sequences", "Proposal and quotation automation", "Live pipeline dashboard", "Stalled-deal alert system", "Lost lead recovery campaign", "AI sales assistant for next actions"],
    impactAreas: ["Revenue capture", "Conversion performance", "Sales productivity", "Forecast confidence", "Customer response speed"],
    systems: ["CRM", "Workflow automation", "Notification system", "BI dashboard", "AI assistant"],
  },
  {
    id: "finance", name: "Finance & Accounting Operations", shortName: "Finance", icon: "coins",
    description: "Automate invoicing, approvals, reconciliation, payment reminders, reporting, and financial control workflows.",
    coreQuestion: "Is your finance function slowing cash flow, increasing errors, or creating avoidable control risk?",
    dimensions: ["Invoice generation", "Accounts receivable", "Accounts payable", "Expense approvals", "Procure-to-pay", "Reconciliation", "Financial close", "Management reporting", "Budget control", "Internal controls"],
    questions: [
      "How structured and automated is your invoice creation and delivery process?",
      "Are invoices linked to sales orders, contracts, or delivery confirmation?",
      "Do customers receive automated payment reminders?",
      "Can finance see overdue invoices in real time?",
      "Do you have a controlled approval workflow for vendor bills and payments?",
      "Are purchase requests, purchase orders, invoices, and payments connected?",
      "How automated is your bank reconciliation process?",
      "How automated is the preparation of routine financial reports?",
      "How structured and timely is your month-end closing process?",
      "Are expense claims submitted and approved digitally?",
      "Are approval limits enforced automatically?",
      "Can management see cash, receivables, payables, and expenses in one dashboard?",
      "Can duplicate invoices or payments be detected before approval?",
      "Are finance exceptions flagged automatically?",
      "Do approvals, payments, and record changes maintain a reliable audit trail?",
    ],
    kpis: ["Days Sales Outstanding", "Invoice processing time", "Payment approval cycle", "Receivables ageing", "Reconciliation time", "Month-end close duration", "Expense approval time", "Manual journal entries", "Report preparation time"],
    opportunities: ["Invoice and payment reminder automation", "Accounts receivable dashboard", "Vendor bill approval workflow", "Expense claim automation", "Procure-to-pay workflow", "Bank reconciliation automation", "Cash flow dashboard", "Budget variance alerts", "Duplicate invoice detection", "AI-assisted report summaries"],
    impactAreas: ["Cash flow", "Financial control", "Processing cost", "Reporting speed", "Error and fraud exposure"],
    systems: ["Accounting software", "Workflow automation", "Document automation", "BI dashboard", "Integration layer"],
  },
  {
    id: "hr", name: "HR Operations", shortName: "HR", icon: "people",
    description: "Automate recruitment, onboarding, attendance, leave, employee requests, payroll inputs, and HR administration.",
    coreQuestion: "Is HR spending too much time on administration instead of workforce performance, compliance, and employee experience?",
    dimensions: ["Recruitment", "Candidate screening", "Onboarding", "Employee records", "Attendance & leave", "Payroll inputs", "Employee requests", "Performance", "Training & compliance", "Offboarding"],
    questions: [
      "How centrally are job applications received and tracked?",
      "Do you have a structured applicant tracking process?",
      "How automated is candidate screening?",
      "Are interview schedules coordinated automatically?",
      "Do new employees follow a tracked onboarding checklist?",
      "Are employee records stored centrally and securely?",
      "Can employees request and track leave digitally?",
      "Is attendance captured digitally and connected to HR records?",
      "Are payroll inputs automatically consolidated from attendance, overtime, deductions, and leave?",
      "Do employees have a self-service channel for HR requests?",
      "Are HR policies easy for employees to access and search?",
      "Are performance reviews structured and tracked?",
      "Can HR see absenteeism, turnover, headcount, and pending requests in real time?",
      "Is offboarding controlled through an assets, access, documents, and final-payment checklist?",
      "Are compliance documents and employee acknowledgements tracked?",
    ],
    kpis: ["Time to hire", "Application-to-interview ratio", "Onboarding completion time", "Leave approval time", "Attendance exception rate", "Payroll error rate", "HR request resolution", "Employee turnover", "Training completion"],
    opportunities: ["Applicant tracking workflow", "AI-assisted CV screening", "Interview scheduling automation", "Digital onboarding workflow", "Employee document management", "Attendance and leave automation", "Payroll input consolidation", "HR helpdesk and policy assistant", "Performance review workflow", "Offboarding and access removal"],
    impactAreas: ["HR productivity", "Employee experience", "Payroll accuracy", "Compliance control", "Time to productivity"],
    systems: ["HRIS", "Workflow automation", "Document automation", "AI assistant", "Notification system"],
  },
  {
    id: "marketing", name: "Marketing Operations", shortName: "Marketing", icon: "target",
    description: "Improve campaign tracking, lead nurturing, attribution, marketing-to-sales handoff, and ROI visibility.",
    coreQuestion: "Is your marketing generating measurable demand, or are campaigns running without clear lead tracking, nurturing, and ROI visibility?",
    dimensions: ["Lead generation", "Landing pages", "Campaign tracking", "Attribution", "Segmentation", "Nurturing", "Content operations", "Social workflow", "Sales handoff", "Performance reporting"],
    questions: [
      "How clearly do you know which channels currently generate qualified leads?",
      "Are campaigns consistently tagged by source, medium, campaign, and channel?",
      "Can you calculate cost per lead reliably?",
      "Can you calculate cost per acquired customer reliably?",
      "Are website, ad, social media, and WhatsApp leads captured centrally?",
      "Are leads segmented by interest, industry, behavior, or readiness to buy?",
      "Do prospects receive automated nurturing after first contact?",
      "Is there a structured content calendar and approval process?",
      "Are campaign assets reviewed through a controlled workflow?",
      "Does marketing automatically notify sales when a qualified lead arrives?",
      "Can you track which campaigns generate actual revenue?",
      "Do you automatically retarget or re-engage inactive prospects?",
      "How automated is marketing report preparation?",
      "Can leadership see campaign performance in real time?",
      "Do you systematically test and optimize campaigns using performance data?",
    ],
    kpis: ["Cost per lead", "Cost per acquisition", "Conversion by channel", "Landing page conversion", "Marketing qualified leads", "Campaign ROI", "Nurture conversion", "Sales handoff time", "Revenue by source"],
    opportunities: ["Central lead capture and CRM integration", "Lead-source tracking", "Automated nurture sequences", "Lead segmentation and scoring", "Campaign performance dashboard", "Marketing-to-sales alerts", "Retargeting audience sync", "AI content workflow support", "Campaign approval workflow", "ROI attribution dashboard"],
    impactAreas: ["Demand generation", "Acquisition efficiency", "Lead conversion", "Marketing productivity", "Revenue attribution"],
    systems: ["CRM", "Workflow automation", "BI dashboard", "Integration layer", "AI assistant"],
  },
  {
    id: "support", name: "Customer Support Operations", shortName: "Support", icon: "headset",
    description: "Reduce missed enquiries, improve response time, automate ticket routing, and improve customer service visibility.",
    coreQuestion: "Are customer enquiries, complaints, and support requests being handled quickly, consistently, and visibly?",
    dimensions: ["Support channels", "Ticket intake", "Classification", "Response time", "Resolution", "Knowledge base", "Escalation", "SLA management", "Customer feedback", "Support analytics"],
    questions: [
      "How clearly can you see all channels customers use to contact you?",
      "Are support requests captured in a ticketing system?",
      "Are WhatsApp, email, phone, website, and social enquiries centralized?",
      "Are tickets categorized automatically?",
      "Are tickets routed to the right person or department automatically?",
      "Do customers receive an immediate automated acknowledgement?",
      "Do you consistently track first response time?",
      "Do you consistently track resolution time?",
      "Can common questions be resolved through reusable approved answers or self-service?",
      "Do you maintain a searchable knowledge base?",
      "Are unresolved issues escalated automatically?",
      "Can managers see overdue tickets and SLA breaches in real time?",
      "Do you collect customer satisfaction feedback consistently?",
      "Can you identify repeat complaints and root causes?",
      "Can support issues be connected to churn, refunds, or lost revenue?",
    ],
    kpis: ["First response time", "Average resolution time", "First-contact resolution", "Ticket backlog", "SLA breach rate", "Repeat contact rate", "Escalation rate", "Customer satisfaction", "Agent workload"],
    opportunities: ["Omnichannel ticketing", "WhatsApp support automation", "AI assistant for common enquiries", "Ticket classification and routing", "SLA reminders and escalation", "Knowledge base automation", "Sentiment detection", "Customer feedback automation", "Support dashboard", "AI reply drafting"],
    impactAreas: ["Customer retention", "Response speed", "Service consistency", "Agent productivity", "Customer insight"],
    systems: ["Helpdesk", "Workflow automation", "AI assistant", "Knowledge base", "BI dashboard"],
  },
  {
    id: "supply-chain", name: "Supply Chain & Logistics Operations", shortName: "Supply Chain", icon: "workflow",
    description: "Improve inventory visibility, dispatch control, supplier performance, delivery tracking, and fulfillment speed.",
    coreQuestion: "Are delays, stock issues, manual dispatching, poor visibility, or supplier problems affecting service delivery and profitability?",
    dimensions: ["Demand planning", "Procurement", "Supplier management", "Inventory", "Warehouse", "Fulfillment", "Dispatch", "Delivery tracking", "Returns", "Exception management"],
    questions: [
      "How data-driven is your demand forecasting and inventory planning?",
      "Are reorder points and low-stock alerts automated?",
      "Are purchase requests and approvals handled digitally?",
      "Can you track supplier delivery performance?",
      "Do you have real-time inventory visibility?",
      "Are stock counts system-driven rather than spreadsheet-driven?",
      "How effectively do your systems prevent stockouts and overstocking?",
      "Are warehouse picking, packing, and dispatch activities tracked?",
      "Are orders assigned to drivers, riders, or logistics partners automatically?",
      "Do customers receive delivery updates automatically?",
      "Do you capture proof of delivery digitally?",
      "Are route plans optimized using reliable data?",
      "Can management see delayed deliveries in real time?",
      "Are returns, damages, and failed deliveries tracked through a workflow?",
      "Can you measure logistics cost per order reliably?",
    ],
    kpis: ["Order cycle time", "On-time delivery", "Order accuracy", "Inventory turnover", "Stockout rate", "Fill rate", "Supplier performance", "Delivery success", "Cost per delivery", "Return rate"],
    opportunities: ["Inventory alerts and reorder workflow", "Supplier portal and scorecard", "Purchase approval automation", "Warehouse scanning", "Pick-pack-dispatch workflow", "Delivery assignment automation", "Route optimization", "Digital proof of delivery", "Customer delivery notifications", "Logistics exception dashboard"],
    impactAreas: ["Working capital", "Fulfillment speed", "Delivery reliability", "Inventory accuracy", "Logistics cost"],
    systems: ["Inventory management", "Logistics management system", "Workflow automation", "Notification system", "BI dashboard"],
  },
  {
    id: "it", name: "IT Operations", shortName: "IT", icon: "code",
    description: "Automate service requests, incident handling, access approvals, asset tracking, monitoring, and IT risk visibility.",
    coreQuestion: "Is your IT function reactive, manual, and invisible until something breaks?",
    dimensions: ["Service desk", "Incident management", "Service requests", "Asset management", "Access management", "Monitoring", "Change management", "Backup & recovery", "Patch management", "Security operations"],
    questions: [
      "How consistently do employees report IT issues through a controlled channel?",
      "Are IT tickets logged in a service desk system?",
      "Are incidents prioritized by urgency and business impact?",
      "Do users receive automatic updates on ticket status?",
      "Are common IT requests automated or self-service?",
      "Are access requests approved through a tracked workflow?",
      "Is employee onboarding and offboarding linked to IT access provisioning?",
      "Do you maintain an accurate, current asset inventory?",
      "Do you continuously monitor servers, websites, applications, networks, and endpoints?",
      "Are monitoring alerts routed automatically to the right person?",
      "Do you track incident response and resolution time?",
      "Are software updates and patches tracked centrally?",
      "Are backups monitored and tested?",
      "Are changes approved and recorded before deployment?",
      "Can leadership see IT risk, uptime, incidents, assets, and security posture in one dashboard?",
    ],
    kpis: ["Uptime", "Incident volume", "Mean time to acknowledge", "Mean time to resolve", "Ticket backlog", "First-contact resolution", "Change failure rate", "Patch compliance", "Backup success", "Asset accuracy"],
    opportunities: ["IT service desk and self-service portal", "Automated ticket routing", "Incident alerts", "Access approval workflows", "User onboarding and offboarding", "Asset inventory automation", "Patch and backup monitoring", "Uptime monitoring", "Security alert workflow", "AI IT support assistant"],
    impactAreas: ["Business continuity", "IT productivity", "Security response", "Employee experience", "Technology risk visibility"],
    systems: ["IT service desk", "Workflow automation", "Monitoring platform", "AI assistant", "BI dashboard"],
  },
];

export const FUNCTION_MAP = Object.fromEntries(ASSESSMENT_FUNCTIONS.map((item) => [item.id, item])) as Record<FunctionId, AssessmentFunction>;

